# Generated by Django 4.0.1 on 2022-02-07 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fundsTransfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='IBAN',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountNo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountOpeningDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountTitle',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='accounts',
            name='availableBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='accounts',
            name='currency',
            field=models.CharField(default='PKR', max_length=5),
        ),
        migrations.AddField(
            model_name='accounts',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
