# Generated by Django 4.0.1 on 2022-02-05 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundsTransfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundsTransfer.accounts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
