# Generated by Django 4.0.1 on 2022-02-07 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=6)),
                ('loan_type', models.CharField(choices=[('ST', 'Short-term'), ('IT', 'Intermediate-term'), ('LT', 'Long-term')], default='Short-term', max_length=20)),
                ('maturity', models.CharField(choices=[('ONE_YEAR', '1'), ('FIVE_YEARS', '5'), ('SEVEN_YEARS', '7'), ('TEN_YEARS', '10')], default='1', max_length=20)),
                ('repayment_schedule', models.CharField(choices=[('ML', 'Monthly'), ('SA', 'Semi-annual')], default='Monthly', max_length=20)),
                ('loan_amount', models.CharField(choices=[('HUNDRED_K', '100000'), ('FIVE_HUNDRED_K', '500000'), ('SEVEN_HUNDRED_K', '700000'), ('ONE_MILLION', '1000000')], default='100000', max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
